// audioProcessor.v

// Generated using ACDS version 18.1 646

`timescale 1 ps / 1 ps
module audioProcessor (
		input  wire [1:0]  bass_stage_switch_export,   //   bass_stage_switch.export
		input  wire        clk_clk,                    //                 clk.clk
		output wire [7:0]  green_leds_export,          //          green_leds.export
		input  wire        i2c_master_serial_sda_in,   //   i2c_master_serial.sda_in
		input  wire        i2c_master_serial_scl_in,   //                    .scl_in
		output wire        i2c_master_serial_sda_oe,   //                    .sda_oe
		output wire        i2c_master_serial_scl_oe,   //                    .scl_oe
		input  wire        mute_button_export,         //         mute_button.export
		output wire [17:0] red_leds_export,            //            red_leds.export
		input  wire [1:0]  treble_stage_switch_export, // treble_stage_switch.export
		input  wire        volume_down_button_export,  //  volume_down_button.export
		input  wire        volume_up_button_export     //    volume_up_button.export
	);

	wire         niosaudioprocessor_debug_reset_request_reset;                     // NIOSAudioProcessor:debug_reset_request -> rst_controller:reset_in0
	wire  [31:0] niosaudioprocessor_data_master_readdata;                          // mm_interconnect_0:NIOSAudioProcessor_data_master_readdata -> NIOSAudioProcessor:d_readdata
	wire         niosaudioprocessor_data_master_waitrequest;                       // mm_interconnect_0:NIOSAudioProcessor_data_master_waitrequest -> NIOSAudioProcessor:d_waitrequest
	wire         niosaudioprocessor_data_master_debugaccess;                       // NIOSAudioProcessor:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOSAudioProcessor_data_master_debugaccess
	wire  [17:0] niosaudioprocessor_data_master_address;                           // NIOSAudioProcessor:d_address -> mm_interconnect_0:NIOSAudioProcessor_data_master_address
	wire   [3:0] niosaudioprocessor_data_master_byteenable;                        // NIOSAudioProcessor:d_byteenable -> mm_interconnect_0:NIOSAudioProcessor_data_master_byteenable
	wire         niosaudioprocessor_data_master_read;                              // NIOSAudioProcessor:d_read -> mm_interconnect_0:NIOSAudioProcessor_data_master_read
	wire         niosaudioprocessor_data_master_write;                             // NIOSAudioProcessor:d_write -> mm_interconnect_0:NIOSAudioProcessor_data_master_write
	wire  [31:0] niosaudioprocessor_data_master_writedata;                         // NIOSAudioProcessor:d_writedata -> mm_interconnect_0:NIOSAudioProcessor_data_master_writedata
	wire  [31:0] niosaudioprocessor_instruction_master_readdata;                   // mm_interconnect_0:NIOSAudioProcessor_instruction_master_readdata -> NIOSAudioProcessor:i_readdata
	wire         niosaudioprocessor_instruction_master_waitrequest;                // mm_interconnect_0:NIOSAudioProcessor_instruction_master_waitrequest -> NIOSAudioProcessor:i_waitrequest
	wire  [17:0] niosaudioprocessor_instruction_master_address;                    // NIOSAudioProcessor:i_address -> mm_interconnect_0:NIOSAudioProcessor_instruction_master_address
	wire         niosaudioprocessor_instruction_master_read;                       // NIOSAudioProcessor:i_read -> mm_interconnect_0:NIOSAudioProcessor_instruction_master_read
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_chipselect;              // mm_interconnect_0:JTAG_avalon_jtag_slave_chipselect -> JTAG:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_avalon_jtag_slave_readdata;                // JTAG:av_readdata -> mm_interconnect_0:JTAG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_waitrequest;             // JTAG:av_waitrequest -> mm_interconnect_0:JTAG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_avalon_jtag_slave_address;                 // mm_interconnect_0:JTAG_avalon_jtag_slave_address -> JTAG:av_address
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_read;                    // mm_interconnect_0:JTAG_avalon_jtag_slave_read -> JTAG:av_read_n
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_write;                   // mm_interconnect_0:JTAG_avalon_jtag_slave_write -> JTAG:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_avalon_jtag_slave_writedata;               // mm_interconnect_0:JTAG_avalon_jtag_slave_writedata -> JTAG:av_writedata
	wire  [31:0] mm_interconnect_0_wm8731_i2c_csr_readdata;                        // wm8731_i2c:readdata -> mm_interconnect_0:wm8731_i2c_csr_readdata
	wire   [3:0] mm_interconnect_0_wm8731_i2c_csr_address;                         // mm_interconnect_0:wm8731_i2c_csr_address -> wm8731_i2c:addr
	wire         mm_interconnect_0_wm8731_i2c_csr_read;                            // mm_interconnect_0:wm8731_i2c_csr_read -> wm8731_i2c:read
	wire         mm_interconnect_0_wm8731_i2c_csr_write;                           // mm_interconnect_0:wm8731_i2c_csr_write -> wm8731_i2c:write
	wire  [31:0] mm_interconnect_0_wm8731_i2c_csr_writedata;                       // mm_interconnect_0:wm8731_i2c_csr_writedata -> wm8731_i2c:writedata
	wire  [31:0] mm_interconnect_0_niosaudioprocessor_debug_mem_slave_readdata;    // NIOSAudioProcessor:debug_mem_slave_readdata -> mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_readdata
	wire         mm_interconnect_0_niosaudioprocessor_debug_mem_slave_waitrequest; // NIOSAudioProcessor:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_niosaudioprocessor_debug_mem_slave_debugaccess; // mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_debugaccess -> NIOSAudioProcessor:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_niosaudioprocessor_debug_mem_slave_address;     // mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_address -> NIOSAudioProcessor:debug_mem_slave_address
	wire         mm_interconnect_0_niosaudioprocessor_debug_mem_slave_read;        // mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_read -> NIOSAudioProcessor:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_niosaudioprocessor_debug_mem_slave_byteenable;  // mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_byteenable -> NIOSAudioProcessor:debug_mem_slave_byteenable
	wire         mm_interconnect_0_niosaudioprocessor_debug_mem_slave_write;       // mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_write -> NIOSAudioProcessor:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_niosaudioprocessor_debug_mem_slave_writedata;   // mm_interconnect_0:NIOSAudioProcessor_debug_mem_slave_writedata -> NIOSAudioProcessor:debug_mem_slave_writedata
	wire         mm_interconnect_0_sram_s1_chipselect;                             // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;                               // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [13:0] mm_interconnect_0_sram_s1_address;                                // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;                             // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;                                  // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;                              // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;                                  // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire         mm_interconnect_0_greenleds_s1_chipselect;                        // mm_interconnect_0:greenLEDs_s1_chipselect -> greenLEDs:chipselect
	wire  [31:0] mm_interconnect_0_greenleds_s1_readdata;                          // greenLEDs:readdata -> mm_interconnect_0:greenLEDs_s1_readdata
	wire   [1:0] mm_interconnect_0_greenleds_s1_address;                           // mm_interconnect_0:greenLEDs_s1_address -> greenLEDs:address
	wire         mm_interconnect_0_greenleds_s1_write;                             // mm_interconnect_0:greenLEDs_s1_write -> greenLEDs:write_n
	wire  [31:0] mm_interconnect_0_greenleds_s1_writedata;                         // mm_interconnect_0:greenLEDs_s1_writedata -> greenLEDs:writedata
	wire         mm_interconnect_0_redleds_s1_chipselect;                          // mm_interconnect_0:redLEDs_s1_chipselect -> redLEDs:chipselect
	wire  [31:0] mm_interconnect_0_redleds_s1_readdata;                            // redLEDs:readdata -> mm_interconnect_0:redLEDs_s1_readdata
	wire   [1:0] mm_interconnect_0_redleds_s1_address;                             // mm_interconnect_0:redLEDs_s1_address -> redLEDs:address
	wire         mm_interconnect_0_redleds_s1_write;                               // mm_interconnect_0:redLEDs_s1_write -> redLEDs:write_n
	wire  [31:0] mm_interconnect_0_redleds_s1_writedata;                           // mm_interconnect_0:redLEDs_s1_writedata -> redLEDs:writedata
	wire  [31:0] mm_interconnect_0_volumeupbutton_s1_readdata;                     // volumeUpButton:readdata -> mm_interconnect_0:volumeUpButton_s1_readdata
	wire   [1:0] mm_interconnect_0_volumeupbutton_s1_address;                      // mm_interconnect_0:volumeUpButton_s1_address -> volumeUpButton:address
	wire  [31:0] mm_interconnect_0_volumedownbutton_s1_readdata;                   // volumeDownButton:readdata -> mm_interconnect_0:volumeDownButton_s1_readdata
	wire   [1:0] mm_interconnect_0_volumedownbutton_s1_address;                    // mm_interconnect_0:volumeDownButton_s1_address -> volumeDownButton:address
	wire  [31:0] mm_interconnect_0_mutebutton_s1_readdata;                         // muteButton:readdata -> mm_interconnect_0:muteButton_s1_readdata
	wire   [1:0] mm_interconnect_0_mutebutton_s1_address;                          // mm_interconnect_0:muteButton_s1_address -> muteButton:address
	wire  [31:0] mm_interconnect_0_bassstageswitch_s1_readdata;                    // bassStageSwitch:readdata -> mm_interconnect_0:bassStageSwitch_s1_readdata
	wire   [1:0] mm_interconnect_0_bassstageswitch_s1_address;                     // mm_interconnect_0:bassStageSwitch_s1_address -> bassStageSwitch:address
	wire  [31:0] mm_interconnect_0_treblestageswitch_s1_readdata;                  // trebleStageSwitch:readdata -> mm_interconnect_0:trebleStageSwitch_s1_readdata
	wire   [1:0] mm_interconnect_0_treblestageswitch_s1_address;                   // mm_interconnect_0:trebleStageSwitch_s1_address -> trebleStageSwitch:address
	wire         irq_mapper_receiver0_irq;                                         // wm8731_i2c:intr -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                         // JTAG:av_irq -> irq_mapper:receiver1_irq
	wire  [31:0] niosaudioprocessor_irq_irq;                                       // irq_mapper:sender_irq -> NIOSAudioProcessor:irq
	wire         rst_controller_reset_out_reset;                                   // rst_controller:reset_out -> [JTAG:rst_n, NIOSAudioProcessor:reset_n, SRAM:reset, bassStageSwitch:reset_n, greenLEDs:reset_n, irq_mapper:reset, mm_interconnect_0:NIOSAudioProcessor_reset_reset_bridge_in_reset_reset, muteButton:reset_n, redLEDs:reset_n, rst_translator:in_reset, trebleStageSwitch:reset_n, volumeDownButton:reset_n, volumeUpButton:reset_n, wm8731_i2c:rst_n]
	wire         rst_controller_reset_out_reset_req;                               // rst_controller:reset_req -> [NIOSAudioProcessor:reset_req, SRAM:reset_req, rst_translator:reset_req_in]

	audioProcessor_JTAG jtag (
		.clk            (clk_clk),                                              //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                      //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                              //               irq.irq
	);

	audioProcessor_NIOSAudioProcessor niosaudioprocessor (
		.clk                                 (clk_clk),                                                          //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                                  //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                               //                          .reset_req
		.d_address                           (niosaudioprocessor_data_master_address),                           //               data_master.address
		.d_byteenable                        (niosaudioprocessor_data_master_byteenable),                        //                          .byteenable
		.d_read                              (niosaudioprocessor_data_master_read),                              //                          .read
		.d_readdata                          (niosaudioprocessor_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (niosaudioprocessor_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (niosaudioprocessor_data_master_write),                             //                          .write
		.d_writedata                         (niosaudioprocessor_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (niosaudioprocessor_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (niosaudioprocessor_instruction_master_address),                    //        instruction_master.address
		.i_read                              (niosaudioprocessor_instruction_master_read),                       //                          .read
		.i_readdata                          (niosaudioprocessor_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (niosaudioprocessor_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (niosaudioprocessor_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (niosaudioprocessor_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                                  // custom_instruction_master.readra
	);

	audioProcessor_SRAM sram (
		.clk        (clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),       // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),   //       .reset_req
		.freeze     (1'b0)                                  // (terminated)
	);

	audioProcessor_bassStageSwitch bassstageswitch (
		.clk      (clk_clk),                                       //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address  (mm_interconnect_0_bassstageswitch_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_bassstageswitch_s1_readdata), //                    .readdata
		.in_port  (bass_stage_switch_export)                       // external_connection.export
	);

	audioProcessor_greenLEDs greenleds (
		.clk        (clk_clk),                                   //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),           //               reset.reset_n
		.address    (mm_interconnect_0_greenleds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_greenleds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_greenleds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_greenleds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_greenleds_s1_readdata),   //                    .readdata
		.out_port   (green_leds_export)                          // external_connection.export
	);

	audioProcessor_muteButton mutebutton (
		.clk      (clk_clk),                                  //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_0_mutebutton_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_mutebutton_s1_readdata), //                    .readdata
		.in_port  (mute_button_export)                        // external_connection.export
	);

	audioProcessor_redLEDs redleds (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address    (mm_interconnect_0_redleds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_redleds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_redleds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_redleds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_redleds_s1_readdata),   //                    .readdata
		.out_port   (red_leds_export)                          // external_connection.export
	);

	audioProcessor_bassStageSwitch treblestageswitch (
		.clk      (clk_clk),                                         //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address  (mm_interconnect_0_treblestageswitch_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_treblestageswitch_s1_readdata), //                    .readdata
		.in_port  (treble_stage_switch_export)                       // external_connection.export
	);

	audioProcessor_muteButton volumedownbutton (
		.clk      (clk_clk),                                        //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                //               reset.reset_n
		.address  (mm_interconnect_0_volumedownbutton_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_volumedownbutton_s1_readdata), //                    .readdata
		.in_port  (volume_down_button_export)                       // external_connection.export
	);

	audioProcessor_muteButton volumeupbutton (
		.clk      (clk_clk),                                      //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address  (mm_interconnect_0_volumeupbutton_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_volumeupbutton_s1_readdata), //                    .readdata
		.in_port  (volume_up_button_export)                       // external_connection.export
	);

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (4),
		.FIFO_DEPTH_LOG2 (2)
	) wm8731_i2c (
		.clk       (clk_clk),                                    //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),            //       reset_sink.reset_n
		.intr      (irq_mapper_receiver0_irq),                   // interrupt_sender.irq
		.addr      (mm_interconnect_0_wm8731_i2c_csr_address),   //              csr.address
		.read      (mm_interconnect_0_wm8731_i2c_csr_read),      //                 .read
		.write     (mm_interconnect_0_wm8731_i2c_csr_write),     //                 .write
		.writedata (mm_interconnect_0_wm8731_i2c_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_wm8731_i2c_csr_readdata),  //                 .readdata
		.sda_in    (i2c_master_serial_sda_in),                   //       i2c_serial.sda_in
		.scl_in    (i2c_master_serial_scl_in),                   //                 .scl_in
		.sda_oe    (i2c_master_serial_sda_oe),                   //                 .sda_oe
		.scl_oe    (i2c_master_serial_scl_oe),                   //                 .scl_oe
		.src_data  (),                                           //      (terminated)
		.src_valid (),                                           //      (terminated)
		.src_ready (1'b0),                                       //      (terminated)
		.snk_data  (16'b0000000000000000),                       //      (terminated)
		.snk_valid (1'b0),                                       //      (terminated)
		.snk_ready ()                                            //      (terminated)
	);

	audioProcessor_mm_interconnect_0 mm_interconnect_0 (
		.clk_50_clk_clk                                       (clk_clk),                                                          //                                     clk_50_clk.clk
		.NIOSAudioProcessor_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                                   // NIOSAudioProcessor_reset_reset_bridge_in_reset.reset
		.NIOSAudioProcessor_data_master_address               (niosaudioprocessor_data_master_address),                           //                 NIOSAudioProcessor_data_master.address
		.NIOSAudioProcessor_data_master_waitrequest           (niosaudioprocessor_data_master_waitrequest),                       //                                               .waitrequest
		.NIOSAudioProcessor_data_master_byteenable            (niosaudioprocessor_data_master_byteenable),                        //                                               .byteenable
		.NIOSAudioProcessor_data_master_read                  (niosaudioprocessor_data_master_read),                              //                                               .read
		.NIOSAudioProcessor_data_master_readdata              (niosaudioprocessor_data_master_readdata),                          //                                               .readdata
		.NIOSAudioProcessor_data_master_write                 (niosaudioprocessor_data_master_write),                             //                                               .write
		.NIOSAudioProcessor_data_master_writedata             (niosaudioprocessor_data_master_writedata),                         //                                               .writedata
		.NIOSAudioProcessor_data_master_debugaccess           (niosaudioprocessor_data_master_debugaccess),                       //                                               .debugaccess
		.NIOSAudioProcessor_instruction_master_address        (niosaudioprocessor_instruction_master_address),                    //          NIOSAudioProcessor_instruction_master.address
		.NIOSAudioProcessor_instruction_master_waitrequest    (niosaudioprocessor_instruction_master_waitrequest),                //                                               .waitrequest
		.NIOSAudioProcessor_instruction_master_read           (niosaudioprocessor_instruction_master_read),                       //                                               .read
		.NIOSAudioProcessor_instruction_master_readdata       (niosaudioprocessor_instruction_master_readdata),                   //                                               .readdata
		.bassStageSwitch_s1_address                           (mm_interconnect_0_bassstageswitch_s1_address),                     //                             bassStageSwitch_s1.address
		.bassStageSwitch_s1_readdata                          (mm_interconnect_0_bassstageswitch_s1_readdata),                    //                                               .readdata
		.greenLEDs_s1_address                                 (mm_interconnect_0_greenleds_s1_address),                           //                                   greenLEDs_s1.address
		.greenLEDs_s1_write                                   (mm_interconnect_0_greenleds_s1_write),                             //                                               .write
		.greenLEDs_s1_readdata                                (mm_interconnect_0_greenleds_s1_readdata),                          //                                               .readdata
		.greenLEDs_s1_writedata                               (mm_interconnect_0_greenleds_s1_writedata),                         //                                               .writedata
		.greenLEDs_s1_chipselect                              (mm_interconnect_0_greenleds_s1_chipselect),                        //                                               .chipselect
		.JTAG_avalon_jtag_slave_address                       (mm_interconnect_0_jtag_avalon_jtag_slave_address),                 //                         JTAG_avalon_jtag_slave.address
		.JTAG_avalon_jtag_slave_write                         (mm_interconnect_0_jtag_avalon_jtag_slave_write),                   //                                               .write
		.JTAG_avalon_jtag_slave_read                          (mm_interconnect_0_jtag_avalon_jtag_slave_read),                    //                                               .read
		.JTAG_avalon_jtag_slave_readdata                      (mm_interconnect_0_jtag_avalon_jtag_slave_readdata),                //                                               .readdata
		.JTAG_avalon_jtag_slave_writedata                     (mm_interconnect_0_jtag_avalon_jtag_slave_writedata),               //                                               .writedata
		.JTAG_avalon_jtag_slave_waitrequest                   (mm_interconnect_0_jtag_avalon_jtag_slave_waitrequest),             //                                               .waitrequest
		.JTAG_avalon_jtag_slave_chipselect                    (mm_interconnect_0_jtag_avalon_jtag_slave_chipselect),              //                                               .chipselect
		.muteButton_s1_address                                (mm_interconnect_0_mutebutton_s1_address),                          //                                  muteButton_s1.address
		.muteButton_s1_readdata                               (mm_interconnect_0_mutebutton_s1_readdata),                         //                                               .readdata
		.NIOSAudioProcessor_debug_mem_slave_address           (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_address),     //             NIOSAudioProcessor_debug_mem_slave.address
		.NIOSAudioProcessor_debug_mem_slave_write             (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_write),       //                                               .write
		.NIOSAudioProcessor_debug_mem_slave_read              (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_read),        //                                               .read
		.NIOSAudioProcessor_debug_mem_slave_readdata          (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_readdata),    //                                               .readdata
		.NIOSAudioProcessor_debug_mem_slave_writedata         (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_writedata),   //                                               .writedata
		.NIOSAudioProcessor_debug_mem_slave_byteenable        (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_byteenable),  //                                               .byteenable
		.NIOSAudioProcessor_debug_mem_slave_waitrequest       (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_waitrequest), //                                               .waitrequest
		.NIOSAudioProcessor_debug_mem_slave_debugaccess       (mm_interconnect_0_niosaudioprocessor_debug_mem_slave_debugaccess), //                                               .debugaccess
		.redLEDs_s1_address                                   (mm_interconnect_0_redleds_s1_address),                             //                                     redLEDs_s1.address
		.redLEDs_s1_write                                     (mm_interconnect_0_redleds_s1_write),                               //                                               .write
		.redLEDs_s1_readdata                                  (mm_interconnect_0_redleds_s1_readdata),                            //                                               .readdata
		.redLEDs_s1_writedata                                 (mm_interconnect_0_redleds_s1_writedata),                           //                                               .writedata
		.redLEDs_s1_chipselect                                (mm_interconnect_0_redleds_s1_chipselect),                          //                                               .chipselect
		.SRAM_s1_address                                      (mm_interconnect_0_sram_s1_address),                                //                                        SRAM_s1.address
		.SRAM_s1_write                                        (mm_interconnect_0_sram_s1_write),                                  //                                               .write
		.SRAM_s1_readdata                                     (mm_interconnect_0_sram_s1_readdata),                               //                                               .readdata
		.SRAM_s1_writedata                                    (mm_interconnect_0_sram_s1_writedata),                              //                                               .writedata
		.SRAM_s1_byteenable                                   (mm_interconnect_0_sram_s1_byteenable),                             //                                               .byteenable
		.SRAM_s1_chipselect                                   (mm_interconnect_0_sram_s1_chipselect),                             //                                               .chipselect
		.SRAM_s1_clken                                        (mm_interconnect_0_sram_s1_clken),                                  //                                               .clken
		.trebleStageSwitch_s1_address                         (mm_interconnect_0_treblestageswitch_s1_address),                   //                           trebleStageSwitch_s1.address
		.trebleStageSwitch_s1_readdata                        (mm_interconnect_0_treblestageswitch_s1_readdata),                  //                                               .readdata
		.volumeDownButton_s1_address                          (mm_interconnect_0_volumedownbutton_s1_address),                    //                            volumeDownButton_s1.address
		.volumeDownButton_s1_readdata                         (mm_interconnect_0_volumedownbutton_s1_readdata),                   //                                               .readdata
		.volumeUpButton_s1_address                            (mm_interconnect_0_volumeupbutton_s1_address),                      //                              volumeUpButton_s1.address
		.volumeUpButton_s1_readdata                           (mm_interconnect_0_volumeupbutton_s1_readdata),                     //                                               .readdata
		.wm8731_i2c_csr_address                               (mm_interconnect_0_wm8731_i2c_csr_address),                         //                                 wm8731_i2c_csr.address
		.wm8731_i2c_csr_write                                 (mm_interconnect_0_wm8731_i2c_csr_write),                           //                                               .write
		.wm8731_i2c_csr_read                                  (mm_interconnect_0_wm8731_i2c_csr_read),                            //                                               .read
		.wm8731_i2c_csr_readdata                              (mm_interconnect_0_wm8731_i2c_csr_readdata),                        //                                               .readdata
		.wm8731_i2c_csr_writedata                             (mm_interconnect_0_wm8731_i2c_csr_writedata)                        //                                               .writedata
	);

	audioProcessor_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.sender_irq    (niosaudioprocessor_irq_irq)      //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (niosaudioprocessor_debug_reset_request_reset), // reset_in0.reset
		.clk            (clk_clk),                                      //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),               // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),           //          .reset_req
		.reset_req_in0  (1'b0),                                         // (terminated)
		.reset_in1      (1'b0),                                         // (terminated)
		.reset_req_in1  (1'b0),                                         // (terminated)
		.reset_in2      (1'b0),                                         // (terminated)
		.reset_req_in2  (1'b0),                                         // (terminated)
		.reset_in3      (1'b0),                                         // (terminated)
		.reset_req_in3  (1'b0),                                         // (terminated)
		.reset_in4      (1'b0),                                         // (terminated)
		.reset_req_in4  (1'b0),                                         // (terminated)
		.reset_in5      (1'b0),                                         // (terminated)
		.reset_req_in5  (1'b0),                                         // (terminated)
		.reset_in6      (1'b0),                                         // (terminated)
		.reset_req_in6  (1'b0),                                         // (terminated)
		.reset_in7      (1'b0),                                         // (terminated)
		.reset_req_in7  (1'b0),                                         // (terminated)
		.reset_in8      (1'b0),                                         // (terminated)
		.reset_req_in8  (1'b0),                                         // (terminated)
		.reset_in9      (1'b0),                                         // (terminated)
		.reset_req_in9  (1'b0),                                         // (terminated)
		.reset_in10     (1'b0),                                         // (terminated)
		.reset_req_in10 (1'b0),                                         // (terminated)
		.reset_in11     (1'b0),                                         // (terminated)
		.reset_req_in11 (1'b0),                                         // (terminated)
		.reset_in12     (1'b0),                                         // (terminated)
		.reset_req_in12 (1'b0),                                         // (terminated)
		.reset_in13     (1'b0),                                         // (terminated)
		.reset_req_in13 (1'b0),                                         // (terminated)
		.reset_in14     (1'b0),                                         // (terminated)
		.reset_req_in14 (1'b0),                                         // (terminated)
		.reset_in15     (1'b0),                                         // (terminated)
		.reset_req_in15 (1'b0)                                          // (terminated)
	);

endmodule
